<h1 style='color:blue'>Assignments related to NumPy</h1>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

<h2 style='color:red'>Creating Array</h2>

#### Create an array of 10 elements with values 10 to 1

In [3]:

np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Create an array of 3 X 3 filled with value 10

In [4]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

#### Create an array of 20 elements with random numbers between 50 and 100

In [5]:
np.random.randint(50,100,20)

array([56, 57, 74, 67, 57, 58, 65, 79, 55, 84, 54, 95, 82, 90, 64, 68, 84,
       60, 73, 60], dtype=int32)

#### Create an array of 10 elements with values between 1 to 25 with uniform interval

In [6]:
np.linspace(1,25,10)

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

<h2 style='color:red'>Indexing and Slicing </h2>

#### Display last 2 rows of a 5,5 array 

In [7]:
ar = np.random.randint(1,100,(5,5))
ar

array([[ 2, 71, 52, 56, 92],
       [52, 59, 69, 87, 21],
       [25, 11,  1, 39, 16],
       [ 2, 65,  3, 64, 83],
       [81, 30, 87, 95, 47]], dtype=int32)

#### Display last 2 columns of 3rd to 5th rows 

In [8]:
ar[-2:,:]

array([[ 2, 65,  3, 64, 83],
       [81, 30, 87, 95, 47]], dtype=int32)

#### Display last column of all alternate rows 

In [9]:
ar[2:5,-2:]

array([[39, 16],
       [64, 83],
       [95, 47]], dtype=int32)

In [10]:
ar[::2,-1]

array([92, 16, 47], dtype=int32)

#### Display rows 0,3,4 and columns 1,3 of 5,5 array

In [11]:
ridx = [0,3,4]
cidx = [1,3]
ar[ridx,1::2]

array([[71, 56],
       [65, 64],
       [30, 95]], dtype=int32)

#### Display all elements where number is even

In [12]:
print(ar[ar%2==0])

[ 2 52 56 92 52 16  2 64 30]


<h2 style='color:red'>Array Operations </h2>

#### Add 1 to all even numbers in the array

In [13]:
even_idx = ar % 2 == 0
ar[even_idx] = ar[even_idx] + 1
ar

array([[ 3, 71, 53, 57, 93],
       [53, 59, 69, 87, 21],
       [25, 11,  1, 39, 17],
       [ 3, 65,  3, 65, 83],
       [81, 31, 87, 95, 47]], dtype=int32)

#### Store square of all elements in the array 

In [14]:
a = np.random.randint(1,30,10)
print(a)
a_squares = a * a
print(a_squares)

[26 23 10 22 16  5 12 28 22 12]
[676 529 100 484 256  25 144 784 484 144]


<h2 style="color:red">Methods of ndarray</h2>

#### Display cumulative sum of elements in array of 10 elements 

In [15]:
a.cumsum()

array([ 26,  49,  59,  81,  97, 102, 114, 142, 164, 176])

#### Display where in a sorted array of 10 elements number 20 fits in

In [16]:
a.sort() # Sorts in place
a.searchsorted(20)

np.int64(5)

#### Display index for maximum and minimum value in an array of 10 elements 

In [17]:
b = np.random.randint(1,10,10)
print(b)
np.where(b==b.max())

[5 9 2 6 3 7 3 7 2 4]


(array([1]),)

#### Display highest value in each row in 5,5 array 

In [18]:
a = np.random.randint(1,50,(5,5))
print(a)
max_avg = a.max(axis=1)
print("Highest value in each row = ", max_avg)

[[16 12 16  3 17]
 [15 34 30 35  3]
 [43 43 22 18 11]
 [17 44 40  8 28]
 [26 47 28 24 30]]
Highest value in each row =  [17 35 43 44 47]


#### Display average of each row 

In [19]:
avg = a.mean(axis=1)
print("Average of each row = ", avg)

Average of each row =  [12.8 23.4 27.4 27.4 31. ]


#### Display all non-zero elements of a 5,5 array

In [20]:
a = np.random.randint(0,5,(5,5))
print(a)
a[a != 0]

[[0 0 4 3 4]
 [0 3 4 0 4]
 [0 3 3 1 4]
 [4 3 4 4 4]
 [4 1 4 3 3]]


array([4, 3, 4, 3, 4, 4, 3, 3, 1, 4, 4, 3, 4, 4, 4, 4, 1, 4, 3, 3],
      dtype=int32)

#### Sort each row of a 5,5 array

In [21]:
a.sort(axis=1)
a

array([[0, 0, 3, 4, 4],
       [0, 0, 3, 4, 4],
       [0, 1, 3, 3, 4],
       [3, 4, 4, 4, 4],
       [1, 3, 3, 4, 4]], dtype=int32)

<h2 style="color:red">Reshaping, stacking and splitting an Array</h2>

#### Reshape an array of 2,6 to 3,4 

In [22]:
a = np.random.randint(1,10,(2,6))
print(a)
a.reshape((3,4))

[[7 7 2 5 2 4]
 [5 4 4 1 4 5]]


array([[7, 7, 2, 5],
       [2, 4, 5, 4],
       [4, 1, 4, 5]], dtype=int32)

#### Convert a 3,3 array to a single dimension array and create a copy

In [23]:
a = np.random.randint(1,10,(3,3))
print(a)
b = a.flatten()
b

[[9 5 2]
 [7 3 6]
 [4 7 7]]


array([9, 5, 2, 7, 3, 6, 4, 7, 7], dtype=int32)

#### Reshape an array of 2,6 to 3,4 inplace

In [24]:
a = np.random.randint(1,10,(2,6))
print(a)
a.resize((3,4))
a

[[9 3 5 9 6 5]
 [5 4 9 9 2 5]]


array([[9, 3, 5, 9],
       [6, 5, 5, 4],
       [9, 9, 2, 5]], dtype=int32)

#### Create an array of 5,5 and transpose it 


In [25]:
a = np.random.randint(1,25,(5,5))
print(a)
a.T

[[13  4  6  5 11]
 [10  8  3  1 14]
 [ 5 19 10  2 22]
 [11 22 11 19 16]
 [ 6  9 22 20  3]]


array([[13, 10,  5, 11,  6],
       [ 4,  8, 19, 22,  9],
       [ 6,  3, 10, 11, 22],
       [ 5,  1,  2, 19, 20],
       [11, 14, 22, 16,  3]], dtype=int32)

#### Split an array of 5,5 into three parts at 2nd and 4th rows 

In [26]:
np.vsplit(a,(2,4))

[array([[13,  4,  6,  5, 11],
        [10,  8,  3,  1, 14]], dtype=int32),
 array([[ 5, 19, 10,  2, 22],
        [11, 22, 11, 19, 16]], dtype=int32),
 array([[ 6,  9, 22, 20,  3]], dtype=int32)]

#### Concatenate two arrays of 3,3 and 4,3 into one array

In [27]:
a = np.random.randint(1,20,(3,3))
print(a)
b = np.random.randint(1,20,(4,3))
print(b)
np.vstack((a,b))

[[ 3  5  6]
 [ 7 17  5]
 [ 5  4  9]]
[[ 9 10  2]
 [17  4 19]
 [15  1 13]
 [ 6  5  2]]


array([[ 3,  5,  6],
       [ 7, 17,  5],
       [ 5,  4,  9],
       [ 9, 10,  2],
       [17,  4, 19],
       [15,  1, 13],
       [ 6,  5,  2]], dtype=int32)

#### Split an array of 6,6 into two parts horizontally

In [28]:
a = np.random.randint(10,50,(6,6))
print(a)
np.hsplit(a,2)

[[29 44 46 21 47 43]
 [39 43 13 42 40 45]
 [43 35 45 14 30 29]
 [39 47 46 26 39 10]
 [24 20 48 23 11 14]
 [32 48 22 14 36 27]]


[array([[29, 44, 46],
        [39, 43, 13],
        [43, 35, 45],
        [39, 47, 46],
        [24, 20, 48],
        [32, 48, 22]], dtype=int32),
 array([[21, 47, 43],
        [42, 40, 45],
        [14, 30, 29],
        [26, 39, 10],
        [23, 11, 14],
        [14, 36, 27]], dtype=int32)]